// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj20XWXwbk1yMaN7wawZYgrKMfesjWkjM',
    appId: '1:177684686258:web:5484c54f8856d10d2d70ab',
    messagingSenderId: '177684686258',
    projectId: 'kickcart-7bafa',
    authDomain: 'kickcart-7bafa.firebaseapp.com',
    storageBucket: 'kickcart-7bafa.appspot.com',
    measurementId: 'G-XJHZ41YZPB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOt5GYb9CeKS37n4_MRko5afQxzKewqOk',
    appId: '1:177684686258:android:9c7a30c900f61b482d70ab',
    messagingSenderId: '177684686258',
    projectId: 'kickcart-7bafa',
    storageBucket: 'kickcart-7bafa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC2eiIMBc85kyVkk71IZn_QTOHL6Uckyk',
    appId: '1:177684686258:ios:06dc7987a68765ab2d70ab',
    messagingSenderId: '177684686258',
    projectId: 'kickcart-7bafa',
    storageBucket: 'kickcart-7bafa.appspot.com',
    iosBundleId: 'com.example.kickcartAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDC2eiIMBc85kyVkk71IZn_QTOHL6Uckyk',
    appId: '1:177684686258:ios:06dc7987a68765ab2d70ab',
    messagingSenderId: '177684686258',
    projectId: 'kickcart-7bafa',
    storageBucket: 'kickcart-7bafa.appspot.com',
    iosBundleId: 'com.example.kickcartAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCj20XWXwbk1yMaN7wawZYgrKMfesjWkjM',
    appId: '1:177684686258:web:6d6cd1a6ac09bcf72d70ab',
    messagingSenderId: '177684686258',
    projectId: 'kickcart-7bafa',
    authDomain: 'kickcart-7bafa.firebaseapp.com',
    storageBucket: 'kickcart-7bafa.appspot.com',
    measurementId: 'G-HPLSWK976V',
  );
}
